### ISSUE TITLE
Delphinus.Install.json is no valid json

### ISSUE THREAD

**Issue by Memnarch** [CWBudde/DWScript#1]
there is at least one wrong comma at the end of the json file. Loading fails on Delphi XE :(
http://jsonlint.com/ reports that it's invalid, too

**Comment by CWBudde** [comment]
This should be fixed now.

**Comment by Memnarch** [comment]
Seems fine. Some notes:
Delphinus is for xe and up, so 2009 and 2010 entry is almost useless.

Is there a reason for no designtimepackages? (Isee the dpk files, but no projects and entries in Delphinus)

Between XE3 and XE7 there are no specific projects. Using compiler_min/compiler_max you could unlock the XE3 project for XE4-6. This works most of the time. 

But deploying source only is no problem. Sometimes its better to be on the safe side.
