### ISSUE TITLE
Which repo to use? (BitBucket/GitHub)

### ISSUE THREAD

**Issue by darianmiller** [CWBudde/DWScript#5]
Doesn't seem obvious - what's the purpose of two different repos?  

The GitHub version seems to have more package files, and extra files for Delphinus but source code differs from Eric's BitBucket repo.

Suggest updating the main readme

**Comment by CWBudde** [comment]
This is my very own fork, which I try to keep synchronized with the main repository every now and then. The difference is not only the package files, but also some other changes, which I made for my own need.

The reason I made it official is the fact that it's license requires to make any changes public. The easiest way for me to do so is to put it here. This gives others the chance to use it as well.

While updating the readme sounds like a good idea, I have actually hardly a clue what to write there (except maybe for the fact that it's my private fork), as I don't want to keep a log of all the changes I made nor do I want to have the pressure to update it regularly.

**Comment by darianmiller** [comment]
Thanks - it will probably save some questions down the line.
